// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpnAEfLm4lmdY25o2UfQmBhxhbrhkE26Y',
    appId: '1:236157181771:web:7ca1252f027033dc4212ce',
    messagingSenderId: '236157181771',
    projectId: 'push-notification-51ccc',
    authDomain: 'push-notification-51ccc.firebaseapp.com',
    storageBucket: 'push-notification-51ccc.appspot.com',
    measurementId: 'G-SFWQ3XVMTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9-7G2I6Q4OaEjmXi4d_R2-MrEuSPz02M',
    appId: '1:236157181771:android:75d01d5c882e0ae94212ce',
    messagingSenderId: '236157181771',
    projectId: 'push-notification-51ccc',
    storageBucket: 'push-notification-51ccc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbjQpIOvS0UN_VcS0VwrtmsruGEHO_xIY',
    appId: '1:236157181771:ios:1e4567a8d803e8cf4212ce',
    messagingSenderId: '236157181771',
    projectId: 'push-notification-51ccc',
    storageBucket: 'push-notification-51ccc.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbjQpIOvS0UN_VcS0VwrtmsruGEHO_xIY',
    appId: '1:236157181771:ios:05afe2d69afcedbc4212ce',
    messagingSenderId: '236157181771',
    projectId: 'push-notification-51ccc',
    storageBucket: 'push-notification-51ccc.appspot.com',
    iosBundleId: 'com.example.pushNotification.RunnerTests',
  );
}
